from skimage import filters, data, io, feature
from skimage.morphology import disk
import matplotlib.pyplot as plt

charA = io.imread('./characterA.jpg')
lena = io.imread('./lena.bmp')

gassian_charA_1 = filters.gaussian(charA, sigma=0.1)
gassian_charA_2 = filters.gaussian(charA, sigma=6)
median_charA = filters.median(charA, disk(3))

plt.figure(figsize=(10, 10))
plt.subplot(221)
plt.imshow(charA, cmap='gray')
plt.title('Original Image')
plt.subplot(222)
plt.imshow(median_charA, cmap='gray')
plt.title('Median Filter (disk=3)')
plt.subplot(223)
plt.imshow(gassian_charA_1, cmap='gray')
plt.title('Gaussian Filter (sigma=0.1)')
plt.subplot(224)
plt.imshow(gassian_charA_2, cmap='gray')
plt.title('Gaussian Filter (sigma=6)')
plt.show()

sobel_lena = filters.sobel(lena)
roberts_lena = filters.roberts(lena)
prewitt_lena = filters.prewitt(lena)
canny_lena = feature.canny(lena, sigma=1)
gabor_lena_real, gabor_lena_imag = filters.gabor(lena, frequency=0.55)

plt.figure(figsize=(10, 10))
plt.subplot(231)
plt.imshow(lena, cmap='gray')
plt.title('Original Image')
plt.subplot(232)
plt.imshow(sobel_lena, cmap='gray')
plt.title('Sobel Filter')
plt.subplot(233)
plt.imshow(roberts_lena, cmap='gray')
plt.title('Roberts Filter')
plt.subplot(234)
plt.imshow(prewitt_lena, cmap='gray')
plt.title('Prewitt Filter')
plt.subplot(235)
plt.imshow(canny_lena, cmap='gray')
plt.title('Canny Filter (sigma=1)')
plt.subplot(236)
plt.imshow(gabor_lena_real, cmap='gray')
plt.title('Gabor Filter (frequency=0.55)')
plt.show()